[project]
name = "brp-amsterdam-integration-tests"
version = "0.1.0"
description = "Integration tests to validate deployment and integration with the RvIG Backend of the BRP Amsterdam API"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "click>=8.3.1",
    "locust>=2.43.1",
]

[build-system]
requires = ["uv_build>=0.9.25,<0.10.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-root = "src"
